[package]
name = "openttd"
version = "0.1.0"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-lzma = "0.5.1"
bytes = "1.0.1"
subslice = "0.2.2"